#!/bin/sh
for file in `find $1 -type f -print`
do
  mv $file $file.orig
  cat $file.orig | sed "s/\([^\.]\)$2/\1$1.$2/g" > $file.step1
  cat $file.step1 | sed "s/^$2/$1.$2/" > $file
  rm -f $file.orig $file.step1
done

