a.out: peanotype.cmo tomExtension.cmo PeanoSimple1.cmo
	ocamlc -o a.out peanotype.cmo tomExtension.cmo PeanoSimple1.cmo

peanotype.cmo: peanotype.ml
	ocamlc -c peanotype.ml

tomExtension.cmo: tomExtension.ml
	ocamlc -c tomExtension.ml

PeanoSimple1.cmo: PeanoSimple1.ml
	ocamlc -c PeanoSimple1.ml
