#!/bin/sh

# launch javac and translates java file references to the corresponding .tom
# one : take care to only translate names for tom source
stuff=" -e s///"
for i in $*; do
	#	echo $i
	if test -f `basename -- $i .java`.t; then
		stuff=" -e s/`basename -- $i .java`\.java/`basename -- $i .java`\.t/ $stuff"
	fi
done

javac $* 2>&1 | sed $stuff
exit ${PIPESTATUS[0]}
