#!/usr/bin/env python

import sys
import os
import pindent
from shutil import copyfile
from tempfile import mkstemp
from stat import *

def get_prefix(filename):
    t = filename.split('.')
    if len(t) > 1:
        return ".".join(t[:-1])
    else:
        return t[0]

for i in range(1,len(sys.argv)):
  if sys.argv[i].endswith('.t'):
    break

tomargs = sys.argv[1:i] 
filename = sys.argv[i] 
args = sys.argv[i+1:] 

cmd = "tom " + " ".join(tomargs) + " -pCode "

prefix = get_prefix(filename)
if prefix.endswith(".py"):
    outfile = prefix
else:
    outfile = prefix + ".py"

if not os.access(outfile,os.F_OK) or os.stat(outfile)[ST_MTIME] < os.stat(filename)[ST_MTIME]:
    f, tmp = mkstemp(".t",prefix)
    os.close(f)
    copyfile(filename,tmp)
    pindent.complete_file(tmp)
    inp, out, err = os.popen3(cmd + " -o %s %s" % (outfile,tmp))
    inp.close()
    sys.stdout.write(out.read())
    sys.stderr.write(err.read())
    pindent.reformat_file(outfile)
    os.remove(outfile + "~")

os.execvp("python", ["python", outfile] + args)
