#!/usr/bin/env python

import sys
import os
import pindent
from shutil import copyfile
from tempfile import mkstemp
from stat import *

def get_prefix(filename):
    t = filename.split('.')
    if len(t) > 1:
        return ".".join(t[:-1])
    else:
        return t[0]

args = []
filenames = []
for a in sys.argv:
    if a.startswith("-"):
        args.append(a)
    else:
        filenames.append(a)

cmd = "tom " + " ".join(args) + " -pCode "

fn = filenames[1]  # only one file
prefix = get_prefix(fn)
if prefix.endswith(".py"):
    outfile = prefix
else:
    outfile = prefix + ".py"

if not os.access(outfile,os.F_OK) or os.stat(outfile)[ST_MTIME] < os.stat(fn)[ST_MTIME]:
    f, tmp = mkstemp(".t",prefix)
    os.close(f)
    copyfile(fn,tmp)
    pindent.complete_file(tmp)
    inp, out, err = os.popen3(cmd + " -o %s %s" % (outfile,tmp))
    inp.close()
    sys.stdout.write(out.read())
    sys.stderr.write(err.read())
    pindent.reformat_file(outfile)

os.execvp("python", ["python", outfile])
